### ISSUE TITLE
Trying to run wcjs-renderer without wcjs-prebuilt results in binding error

### ISSUE THREAD

**Issue by mattsfrey** [Magics-Group/wcjs-renderer#12]
Currently when trying to run the renderer standalone after building, I encounter this error on load:

```
/Users/matt/wcjs-test/electron-quick-start/node_modules/wcjs-renderer/node_modules/webchimera.js/node_modules/bindings/bindings.js:86
Uncaught Error: Module version mismatch. Expected 47, got 43.
```

I can get the renderer to work when using the wcjs-prebuilt, however I am encountering a separate issue there when attempting to run after browserifying.

Any insights into what this is about or how to fix?

**Comment by mattsfrey** [comment]
I was able to get it working by manually copying the latest prebuilt tar.gz over the local build:

https://github.com/RSATom/WebChimera.js/releases/download/v0.2.3/WebChimera.js_v0.2.3_electron_v0.37.2_VLC_v2.2.2_x64_osx.tar.gz

And realized in the process I'm being moronic and trying to browserify a binary file, so a new overall solution is going to be necessary on my end, probably ditching browserify. Sorry for the unnecessary issue.

**Comment by jaruba** [comment]
```
Uncaught Error: Module version mismatch. Expected 47, got 43.
```

I've been getting this error a lot lately, on a lot of modules. I started getting it after updating `npm` to latest. They seem to have changed something that breaks `npm install` on a lot of modules.

It happens even if there is a correct `@` version in `package.json`, it just wants a specific different version for god knows what reason, I'm counting it as a `npm` bug.

**Comment by RSATom** [comment]
> Uncaught Error: Module version mismatch. Expected 47, got 43.

This means you try use native module builded for one Electron version with another Electron version ( newer or older )

**Comment by RSATom** [comment]
i.e. it's ABI compatibility error
