### ISSUE TITLE
Scale Video

### ISSUE THREAD

**Issue by freemountain** [Magics-Group/wcjs-renderer#8]
Is it possible to scale the video output to canvas size?
I think that this could be done in the onFrameReady callback, but i am not sure.

**Comment by jaruba** [comment]
I'm not sure what you mean, isn't it the size of the canvas all the time?
Can you post a screenshot of your issue?

**Comment by freemountain** [comment]
You are right, i had a problem in my css file.
If i set width and height on the canvas, i can render the video output with the desired dimensions.
Thank you for the quick response!

**Comment by jaruba** [comment]
Cool, glad you got it working. :)

**Comment by mattsfrey** [comment]
Is this still how the renderer is functioning? When I change the canvas.width or canvas.height, it just cuts off the video if it is smaller than the rendering frame or grows larger than it. 

I have been able to resize the video by hooking the onFrameSetup function and passing in a custom width/height and then doing a player.stop() followed by a player.play() and then setting the position to the previous position, but this seems really hacky and doesn't perform well. Is there no legit way to just dynamically resize the frame to desired dimensions? 

EDIT: sorry, realized afterwards that you must change canvas.style.width / canvas.style.height and then it will resize properly.
